# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Audrey Welch, iOS Developer
description: Current iOS Developer. Former ESL Teacher. This is where I track my continuous discoveries. ❤
github_username: audreywelch

# Email and twitter are optional:
email: welch.audreyl@gmail.com
twitter_username: @aud_codes
linkedIn_profile: https://www.linkedin.com/in/audrey-welch-ios/

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

